# gui_config.py
text_strings = {
    "english": {
        "app_title": "Safety & Privacy Toolkit",
        "nav_sms": "SMS Analysis",
        "nav_sentiment": "Sentiment Analysis",
        "nav_fake_pic": "Fake Image Detection",
        "nav_fake_call": "Fake Call Detection",
        "hindi_button": "हिंदी में बदलें",
        "english_button": "Change to English",
        "sms_input_label": "Paste SMS Text Here:",
        "sms_analyze_button": "Analyze SMS",
        "result_label": "Analysis Result:",
        "loading_text": "Analyzing message with AI...",
        "error_text": "Error: Could not analyze message. Please try again.",
        "empty_text": "Please enter an SMS message to analyze.",
        "safe_message": "✅ This message appears to be safe. No obvious spam or phishing indicators detected.",
        "warning_message": "⚠️ CAUTION: This message shows suspicious characteristics.",
        "danger_message": "🚨 HIGH RISK: This message appears to be malicious!",
        "spam_indicators": "Spam indicators detected",
        "phishing_indicators": "Phishing indicators",
        "sentiment_label": "Sentiment",
        "positive_sentiment": "Positive",
        "negative_sentiment": "Negative",
        "neutral_sentiment": "Neutral",
        "stats_length": "Message length",
        "stats_words": "Words",
        "stats_spam": "Spam indicators",
        "stats_phishing": "Phishing indicators",
        "characters": "characters",
        "clear_button": "Clear",
        "contains_links": "Contains links",
        "suspicious_numbers": "Contains suspicious numbers",
        "urgent_language": "Urgent language detected"
    },
    "hindi": {
        "app_title": "सुरक्षा और गोपनीयता टूलकिट",
        "nav_sms": "एसएमएस विश्लेषण",
        "nav_sentiment": "भावना विश्लेषण",
        "nav_fake_pic": "नकली छवि पहचान",
        "nav_fake_call": "नकली कॉल पहचान",
        "hindi_button": "Change to English",
        "english_button": "अंग्रेजी में बदलें",
        "sms_input_label": "एसएमएस टेक्स्ट यहाँ पेस्ट करें:",
        "sms_analyze_button": "एसएमएस का विश्लेषण करें",
        "result_label": "विश्लेषण परिणाम:",
        "loading_text": "AI के साथ संदेश का विश्लेषण किया जा रहा है...",
        "error_text": "त्रुटि: संदेश का विश्लेषण नहीं किया जा सका। कृपया पुनः प्रयास करें।",
        "empty_text": "कृपया विश्लेषण के लिए एक एसएमएस संदेश दर्ज करें।",
        "safe_message": "✅ यह संदेश सुरक्षित प्रतीत होता है। कोई स्पष्ट स्पैम या फ़िशिंग संकेतक नहीं मिले।",
        "warning_message": "⚠️ सावधानी: यह संदेश संदिग्ध विशेषताएं दिखाता है।",
        "danger_message": "🚨 उच्च जोखिम: यह संदेश दुर्भावनापूर्ण प्रतीत होता है!",
        "spam_indicators": "स्पैम संकेतक मिले",
        "phishing_indicators": "फ़िशिंग संकेतक",
        "sentiment_label": "भावना",
        "positive_sentiment": "सकारात्मक",
        "negative_sentiment": "नकारात्मक",
        "neutral_sentiment": "तटस्थ",
        "stats_length": "संदेश लंबाई",
        "stats_words": "शब्द",
        "stats_spam": "स्पैम संकेतक",
        "stats_phishing": "फ़िशिंग संकेतक",
        "characters": "अक्षर",
        "clear_button": "साफ़ करें",
        "contains_links": "लिंक शामिल हैं",
        "suspicious_numbers": "संदिग्ध नंबर शामिल हैं",
        "urgent_language": "अत्यावश्यक भाषा का पता चला"
    }
}